package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;
import javafx.stage.Stage;
import javafx.event.ActionEvent;

public class AddPatientController {

    @FXML
    private  TextField add;

    @FXML
    private  TextField add2;

    @FXML
    private  TextField city;

    @FXML
    private  TextField dob;

    @FXML
    private  TextField email;

    @FXML
    private  Button exitButton;

    @FXML
    private  TextField firstName;

    @FXML
    private  TextField lastName;

    @FXML
    private  TextField num;

    @FXML
    private  Button okButton;

    @FXML
    private  TextField state;

    @FXML
    private  TextField zip;
    
	/*public void AddPatientController() {
		try {
			Parent addpn = FXMLLoader.load(getClass().getResource("Edit Patient Information.fxml"));
			Stage stage = new Stage();
			stage.setTitle("Add Patient");
			stage.setScene(new Scene(addpn));
			stage.show();
		}
		catch(Exception e) {
			e.printStackTrace();
			System.out.println("ERROR: Can not load Patient Add");
		}
	}*/
	

	// Event Listener on Button.onAction
	@FXML
	public  void saveInfo(ActionEvent event) {
		// TODO Autogenerated
		Patient tempPatient;
		
		if(!firstName.getText().isEmpty() && !lastName.getText().isEmpty() && !dob.getText().isEmpty()
				&& !state.getText().isEmpty() && !zip.getText().isEmpty() && !email.getText().isEmpty()
				&& !add.getText().isEmpty() && !city.getText().isEmpty() && !num.getText().isEmpty()) {
		}
		
		else {
			System.out.println("ERROR: not all fields are filled!");
		}
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void exitStage(ActionEvent event) {
		// TODO Autogenerated
		Stage stage = (Stage) exitButton.getScene().getWindow();
		stage.close();
	}
	
}
