package application;

import javafx.fxml.FXML;
import javafx.event.ActionEvent;
import javafx.scene.control.TextArea;
import javafx.stage.Stage;
import javafx.scene.Node;

public class AllergiesAndHealthConcernsController {
	@FXML
	private TextArea allergiesTxt;
	@FXML
	private TextArea hlthCncnTxt;
	@FXML
	private TextArea prevIssuesTxt;
	@FXML
	private TextArea ImmunHisTxt;
	@FXML
	private TextArea prevMedPresTxt;

	// Event Listener on Button.onAction
	@FXML
	public void submitInfo(ActionEvent event) {
		// TODO Autogenerated
		
		
		
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void closeWindow(ActionEvent event) {
		Stage stage = (Stage)((Node)event.getSource()).getScene().getWindow();
		stage.close();
	}
}
