package application;

import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.event.ActionEvent;
import javafx.scene.control.ListView;
import javafx.scene.control.TextArea;
import java.net.URI;
import java.net.URISyntaxException;

import java.awt.*;
import java.io.IOException;


public class MessageCenterController {
	@FXML
	private ListView<String> msgList;
	@FXML
	private Button deletemsgbutton;
	@FXML
	private Button emailbutton;
	@FXML
	private TextArea readMsgBox;
	@FXML
	private TextArea writeMsgBox;
	@FXML
	private Button replybutton;
	@FXML
	private Button newmsgbutton;

	// Event Listener on Button[#deletemsgbutton].onAction
	@FXML
	public void deleteMessage(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#emailbutton].onAction
	@FXML
	public void emailUser(ActionEvent event) {
		try {
			Desktop.getDesktop().browse(new URI("http://www.gmail.com"));
		} catch (IOException e) {
			e.printStackTrace();
		} catch (URISyntaxException e) {
			e.printStackTrace();
		}
		
	}
	// Event Listener on Button[#replybutton].onAction
	@FXML
	public void ReplyToMessage(ActionEvent event) {
		Message msg = new Message();
		msg.messageContent = writeMsgBox.getText();
		//msg.msgFrom = this user
		//msg.msgTo = msgFrom from the list of messages
		
		//Then, we can push the msg onto the User's ArrayList<Message>
		
		
	}
	// Event Listener on Button[#newmsgbutton].onAction
	@FXML
	public void newMessage(ActionEvent event) {
		// TODO Autogenerated
	}
}
