package application;

import javafx.fxml.FXML;
import javafx.scene.Node;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;
import javafx.stage.Stage;

import java.util.ArrayList;
import java.util.List;

import javafx.event.ActionEvent;
import javafx.scene.control.TextArea;


public class PrescribedMedicationController {
	@FXML
	private Button okbutton;
	@FXML
	private Button cancelbutton;
	@FXML
	private TextArea Note;
	@FXML
	private TextField medName;
	@FXML
	private TextField dosage;
	@FXML
	private TextField amount;
	@FXML
	private TextField datePrescr;
	@FXML
	private TextField Reason;
	
	private Patient patient;

	// Event Listener on Button[#okbutton].onAction
	@FXML
	public void SubmitMed(ActionEvent event) {
		// TODO Autogenerated
		Stage stage = (Stage)((Node)event.getSource()).getScene().getWindow();
		List<Prescription> tempList;
		Prescription tempPres;
		
		
		if(!Note.getText().isEmpty() && !medName.getText().isEmpty() && !dosage.getText().isEmpty()
				&& !amount.getText().isEmpty() && !datePrescr.getText().isEmpty() && !Reason.getText().isEmpty()) {
			if(patient.getPrescriptionList() == null) tempList = new ArrayList<Prescription>();
			else tempList = patient.getPrescriptionList();
			tempPres = new Prescription(medName.getText(), Note.getText(), Integer.parseInt(dosage.getText()), Integer.parseInt(amount.getText()),
					datePrescr.getText(), Reason.getText());
			tempList.add(tempPres);
			patient.setPrescriptionList(tempList);
			stage.close();
		}
		else System.out.println("ERROR: Not All Fields Are Filled!");
	}
	// Event Listener on Button[#cancelbutton].onAction
	@FXML
	public void cancelMed(ActionEvent event) {
		// TODO Autogenerated
		Stage stage = (Stage)((Node)event.getSource()).getScene().getWindow();
		stage.close();
	}
	
    public void setPatient(Patient p) {
    	patient = p;
    }
}
